#!/bin/bash
# Utility functions for use in the cartridge scripts.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

function update_configuration {
  /bin/true
}

# RHEL OpenShift Online supported versions
function postgresql_context {
  /bin/true
}
